set -g tide_context_bg_color 1C1C1C
set -g tide_git_bg_color 8db226
set -g tide_git_bg_color_unstable 8db226
set -g tide_git_bg_color_urgent 8db226
set -g tide_git_color_branch 000000
set -g tide_git_color_conflicted 000000
set -g tide_git_color_dirty 000000
set -g tide_git_color_operation 000000
set -g tide_git_color_staged 000000
set -g tide_git_color_stash 000000
set -g tide_git_color_untracked 000000
set -g tide_git_color_upstream 000000
set -g tide_left_prompt_frame_enabled false
set -g tide_left_prompt_items pwd git newline character
set -g tide_left_prompt_prefix \ue0b6
set -g tide_left_prompt_separator_diff_color \ue0bc
set -g tide_left_prompt_separator_same_color \ue0b1
set -g tide_left_prompt_suffix \ue0b0
set -g tide_character_icon '❯'
set -g tide_character_color_failure FF0000
set -g tide_character_color 00FF00
set -g tide_node_bg_color 75507B
set -g tide_node_color 2E3436
set -g tide_os_bg_color CED7CF
set -g tide_os_color 080808
set -g tide_prompt_add_newline_before true
set -g tide_prompt_pad_items true
set -g tide_pwd_bg_color 696969
set -g tide_pwd_color_anchors E4E4E4
set -g tide_pwd_color_dirs a4a4a4
set -g tide_pwd_color_truncated_dirs BCBCBC
set -g tide_pwd_markers .git
set -g tide_right_prompt_items  virtual_env vi_mode
set -g tide_right_prompt_prefix \ue0b2
set -g tide_right_prompt_separator_diff_color \ue0ba
set -g tide_right_prompt_separator_same_color \ue0b3
set -g tide_right_prompt_suffix \ue0b4
set -g tide_vi_mode_bg_color_default 008000
# set -g tide_vi_mode_bg_color_insert 444444
set -g tide_vi_mode_bg_color_replace 808000
set -g tide_vi_mode_bg_color_visual 000080
set -g tide_vi_mode_color_default 000000
set -g tide_vi_mode_color_replace 000000
set -g tide_vi_mode_color_visual 000000
set -g tide_vi_mode_icon_default DEFAULT
set -g tide_vi_mode_icon_replace REPLACE
set -g tide_vi_mode_icon_visual VISUAL
set -g tide_virtual_env_bg_color 444444
set -g tide_git_icon " \uE0A0"
